basler_controller:
        ros__parameters:
                left_serial_number: "40196214"
                rotate_left_camera: True
                right_serial_number: "40196268"
                rotate_right_camera: False
